[project]
name = "AutoChain"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.vehicle-registry]
path = "contracts/vehicle-registry.clar"
depends_on = []

[contracts.vehicle-transfer]
path = "contracts/vehicle-transfer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
